[EXT] Use /tmp folder for logs by default
Running test cluster for integration tests was failing for me with the following errors:

```
java.io.FileNotFoundException: /var/log/elasticsearch/elasticsearch-test-eugenes-macbook-pro-2.local.log (Permission denied)
java.io.FileNotFoundException: /var/log/elasticsearch/elasticsearch-test-eugenes-macbook-pro-2.local_index_indexing_slowlog.log (Permission denied)
java.io.FileNotFoundException: /var/log/elasticsearch/elasticsearch-test-eugenes-macbook-pro-2.local_index_search_slowlog.log (Permission denied)
```

Unlike `/var`, `/tmp` is much more permissive, thus the following fixed the issue I was having:

```bash
TEST_CLUSTER_LOGS=/tmp/logs/elasticsearch rake test:cluster:start
```

Closes #261