[Tests] Skips jbuilder for specific version of JRuby
There is a dependency issue with JBuilder and JRuby 9.4.15.0 at the
moment. This breaks the build unrelated to recent changes. A patch
release is needed, so will investigate.

NoMethodError: undefined method `[]' for Fiber:Class