[CLIENT] Fixed an error where passing `host: { ... }` resulted in error in Client#__extract_hosts
This no longer raises the surprising exception:

  Elasticsearch::Client.new host: { host: 'myhost.com', scheme: 'https' }
  ArgumentError: Please pass host as a String, URI or Hash -- Array given.